version: "3"
services:
  sonarqube:
    image: sonarqube:9.8.0-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - ./sonarqube-data:/opt/sonarqube/data
      - ./sonarqube-extensions:/opt/sonarqube/extensions
      - ./sonarqube-logs:/opt/sonarqube/logs
